name: OutcastsFinale
version: '${project.version}'
main: dev.acronical.outcastsfinale.OutcastsFinale
api-version: '1.20'
author: Acronical
description: The plugin for the Outcasts' Events Finale.
website: https://acronical.is-a.dev/projects
commands:
  pvp:
    description: Enable or disable PVP.
    usage: /pvp <on/off>
    permission: outcastsfinale.pvptoggle
  crownreset:
    description: Allows players to use the crown again.
    usage: /crownreset
    permission: outcastsfinale.crownreset
    aliases:
      - resetcrown
  mealreset:
    description: Allows players to use the meal again.
    usage: /mealreset
    permission: outcastsfinale.mealreset
    aliases:
      - resetmeal
permissions:
    outcastsfinale.pvptoggle:
        description: Allows the player to toggle PVP.
        default: op
    outcastsfinale.crownreset:
        description: Allows the player to reset the crown.
        default: op
    outcastsfinale.mealreset:
        description: Allows the player to reset the meal.
        default: op